// Generated by CoffeeScript 1.7.1
define(['localdb'], function(localDB) {
  describe("Test Case", function() {
    it("expectation", function() {
      expect(localDB).toBe("hello");
    });
  });
});
