// Generated by CoffeeScript 1.7.1
module.exports = function(config) {
  return config.set({
    basePath: '',
    frameworks: ['jasmine', 'requirejs'],
    files: [
      {
        pattern: 'test/**/*Spec.js',
        included: false
      }, 'test-main.js'
    ],
    exclude: [],
    preprocessors: {},
    reporters: ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: ['Chrome'],
    singleRun: true,
    captureTimeout: 6000
  });
};
